### ISSUE TITLE
Bekomme den Adapter nicht Installiert

### ISSUE THREAD

**Issue by mastermix10** [michelde/telenot#22]
Hallo Leute, ich bekomme den Adapter nicht in der Version 5.3.8 nicht installiert. Bin totaler Neuling auf dem iobroker Gebiet. Kann mir jemand bitte weiterhelfen ob ich etwas falsch mache bei der Installation oder gibt es ein Version Konflikt. Andere Adapter lassen sich installieren. Gruß

**Comment by michelde** [comment]
This is no adapter for iobroker.
