### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by cd-tronic** [michelde/telenot#5]
Hi @michelde 

sorry for contacting you again.
Can you please explain a bit more how to configure everything?

![image](https://user-images.githubusercontent.com/7304760/92909685-a48fa280-f427-11ea-9647-f4026c5f2518.png)
![image](https://user-images.githubusercontent.com/7304760/92909768-b7a27280-f427-11ea-99d4-d87f00506d7c.png)

this is what my C400 config looks like. 

I think i need to edit the config/config.js file?
![image](https://user-images.githubusercontent.com/7304760/92909965-eb7d9800-f427-11ea-9fcd-092f1f39d596.png)

what value does "position" stand for?

The communication to the telnet seem to work because the RX/TX counter of my tcp/serial bridge counts up all the time.
But it looks like I'm not getting any MQTT messages at the moment

Regards,

**Comment by michelde** [comment]
Hi, 

As I'm not sure if the settings are the same for every Telenot device you need to figure out the position for your relevant "things". This can be done by:
- You need to set the env-variable DISCOVER = true and LOG_LEVEL should be DEBUG.
- Now open a door or move to the room to trigger the presence detector
- In the log from the application you see the bit-position which has changed.

You can also check if this works for you (I adjusted to your config):

``` 
MELDEBEREICHE: {
      name: 'MELDEBEREICHE',
      positions: [
        { position: 602, name: 'Tür 1 offen', topic: 'tuer1_offen', inverted: true },
      ],
    },
MELDEGRUPPEN: {
      name: 'MELDEGRUPPEN',
      positions: [
        { position: 1080, name: 'BWM1 - Werkstatt', topic: 'bwm1_werkstatt, inverted: true },
        { position: 1125, name: 'Tor offen', topic: 'tor_offen', inverted: true },
      ],
    },
```

**Comment by cd-tronic** [comment]
Hi @michelde,

thank you very much!
